### ISSUE TITLE
Question: Why SIGKILL?

### ISSUE THREAD

**Issue by jkroepke** [ags131/docker-screeps-server#2]
Hi!

why you do catch the SIGTERM from the docker and kills the node process manually? With SIGKILL ?

https://github.com/ags131/docker-screeps-server/blob/master/entrypoint.sh#L4

**Comment by AlinaNova21** [comment]
Looking at it, it should probably just do a SIGTERM instead, thas mostly so that the docker container exits quicker, without it docker waits 10 seconds then sigkills the entire tree
